// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grid.proto

package proto;

public final class GridProto {
  private GridProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GridOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Grid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     */
    int getIndex();

    /**
     * <code>int32 col = 2;</code>
     */
    int getCol();

    /**
     * <code>int32 row = 3;</code>
     */
    int getRow();

    /**
     * <code>repeated .Line lines = 7;</code>
     */
    java.util.List<proto.GridProto.Line> 
        getLinesList();
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    proto.GridProto.Line getLines(int index);
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    int getLinesCount();
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    java.util.List<? extends proto.GridProto.LineOrBuilder> 
        getLinesOrBuilderList();
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    proto.GridProto.LineOrBuilder getLinesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Grid}
   */
  public  static final class Grid extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Grid)
      GridOrBuilder {
    // Use Grid.newBuilder() to construct.
    private Grid(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Grid() {
      index_ = 0;
      col_ = 0;
      row_ = 0;
      lines_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Grid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              index_ = input.readInt32();
              break;
            }
            case 16: {

              col_ = input.readInt32();
              break;
            }
            case 24: {

              row_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                lines_ = new java.util.ArrayList<proto.GridProto.Line>();
                mutable_bitField0_ |= 0x00000008;
              }
              lines_.add(
                  input.readMessage(proto.GridProto.Line.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          lines_ = java.util.Collections.unmodifiableList(lines_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GridProto.internal_static_Grid_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GridProto.internal_static_Grid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GridProto.Grid.class, proto.GridProto.Grid.Builder.class);
    }

    private int bitField0_;
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>int32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int COL_FIELD_NUMBER = 2;
    private int col_;
    /**
     * <code>int32 col = 2;</code>
     */
    public int getCol() {
      return col_;
    }

    public static final int ROW_FIELD_NUMBER = 3;
    private int row_;
    /**
     * <code>int32 row = 3;</code>
     */
    public int getRow() {
      return row_;
    }

    public static final int LINES_FIELD_NUMBER = 7;
    private java.util.List<proto.GridProto.Line> lines_;
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    public java.util.List<proto.GridProto.Line> getLinesList() {
      return lines_;
    }
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    public java.util.List<? extends proto.GridProto.LineOrBuilder> 
        getLinesOrBuilderList() {
      return lines_;
    }
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    public int getLinesCount() {
      return lines_.size();
    }
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    public proto.GridProto.Line getLines(int index) {
      return lines_.get(index);
    }
    /**
     * <code>repeated .Line lines = 7;</code>
     */
    public proto.GridProto.LineOrBuilder getLinesOrBuilder(
        int index) {
      return lines_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      if (col_ != 0) {
        output.writeInt32(2, col_);
      }
      if (row_ != 0) {
        output.writeInt32(3, row_);
      }
      for (int i = 0; i < lines_.size(); i++) {
        output.writeMessage(7, lines_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (col_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, col_);
      }
      if (row_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, row_);
      }
      for (int i = 0; i < lines_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, lines_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.GridProto.Grid)) {
        return super.equals(obj);
      }
      proto.GridProto.Grid other = (proto.GridProto.Grid) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      result = result && (getCol()
          == other.getCol());
      result = result && (getRow()
          == other.getRow());
      result = result && getLinesList()
          .equals(other.getLinesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + COL_FIELD_NUMBER;
      hash = (53 * hash) + getCol();
      hash = (37 * hash) + ROW_FIELD_NUMBER;
      hash = (53 * hash) + getRow();
      if (getLinesCount() > 0) {
        hash = (37 * hash) + LINES_FIELD_NUMBER;
        hash = (53 * hash) + getLinesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.GridProto.Grid parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Grid parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Grid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Grid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Grid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Grid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Grid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GridProto.Grid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GridProto.Grid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.GridProto.Grid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GridProto.Grid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GridProto.Grid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.GridProto.Grid prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Grid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Grid)
        proto.GridProto.GridOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GridProto.internal_static_Grid_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GridProto.internal_static_Grid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GridProto.Grid.class, proto.GridProto.Grid.Builder.class);
      }

      // Construct using proto.GridProto.Grid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLinesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        index_ = 0;

        col_ = 0;

        row_ = 0;

        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          linesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GridProto.internal_static_Grid_descriptor;
      }

      public proto.GridProto.Grid getDefaultInstanceForType() {
        return proto.GridProto.Grid.getDefaultInstance();
      }

      public proto.GridProto.Grid build() {
        proto.GridProto.Grid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.GridProto.Grid buildPartial() {
        proto.GridProto.Grid result = new proto.GridProto.Grid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.index_ = index_;
        result.col_ = col_;
        result.row_ = row_;
        if (linesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            lines_ = java.util.Collections.unmodifiableList(lines_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.lines_ = lines_;
        } else {
          result.lines_ = linesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GridProto.Grid) {
          return mergeFrom((proto.GridProto.Grid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GridProto.Grid other) {
        if (other == proto.GridProto.Grid.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getCol() != 0) {
          setCol(other.getCol());
        }
        if (other.getRow() != 0) {
          setRow(other.getRow());
        }
        if (linesBuilder_ == null) {
          if (!other.lines_.isEmpty()) {
            if (lines_.isEmpty()) {
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureLinesIsMutable();
              lines_.addAll(other.lines_);
            }
            onChanged();
          }
        } else {
          if (!other.lines_.isEmpty()) {
            if (linesBuilder_.isEmpty()) {
              linesBuilder_.dispose();
              linesBuilder_ = null;
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000008);
              linesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLinesFieldBuilder() : null;
            } else {
              linesBuilder_.addAllMessages(other.lines_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.GridProto.Grid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.GridProto.Grid) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int index_ ;
      /**
       * <code>int32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private int col_ ;
      /**
       * <code>int32 col = 2;</code>
       */
      public int getCol() {
        return col_;
      }
      /**
       * <code>int32 col = 2;</code>
       */
      public Builder setCol(int value) {
        
        col_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 col = 2;</code>
       */
      public Builder clearCol() {
        
        col_ = 0;
        onChanged();
        return this;
      }

      private int row_ ;
      /**
       * <code>int32 row = 3;</code>
       */
      public int getRow() {
        return row_;
      }
      /**
       * <code>int32 row = 3;</code>
       */
      public Builder setRow(int value) {
        
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 row = 3;</code>
       */
      public Builder clearRow() {
        
        row_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<proto.GridProto.Line> lines_ =
        java.util.Collections.emptyList();
      private void ensureLinesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          lines_ = new java.util.ArrayList<proto.GridProto.Line>(lines_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.GridProto.Line, proto.GridProto.Line.Builder, proto.GridProto.LineOrBuilder> linesBuilder_;

      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public java.util.List<proto.GridProto.Line> getLinesList() {
        if (linesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lines_);
        } else {
          return linesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public int getLinesCount() {
        if (linesBuilder_ == null) {
          return lines_.size();
        } else {
          return linesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public proto.GridProto.Line getLines(int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);
        } else {
          return linesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder setLines(
          int index, proto.GridProto.Line value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.set(index, value);
          onChanged();
        } else {
          linesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder setLines(
          int index, proto.GridProto.Line.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.set(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder addLines(proto.GridProto.Line value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(value);
          onChanged();
        } else {
          linesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder addLines(
          int index, proto.GridProto.Line value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(index, value);
          onChanged();
        } else {
          linesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder addLines(
          proto.GridProto.Line.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder addLines(
          int index, proto.GridProto.Line.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder addAllLines(
          java.lang.Iterable<? extends proto.GridProto.Line> values) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lines_);
          onChanged();
        } else {
          linesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder clearLines() {
        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          linesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public Builder removeLines(int index) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.remove(index);
          onChanged();
        } else {
          linesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public proto.GridProto.Line.Builder getLinesBuilder(
          int index) {
        return getLinesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public proto.GridProto.LineOrBuilder getLinesOrBuilder(
          int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);  } else {
          return linesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public java.util.List<? extends proto.GridProto.LineOrBuilder> 
           getLinesOrBuilderList() {
        if (linesBuilder_ != null) {
          return linesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lines_);
        }
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public proto.GridProto.Line.Builder addLinesBuilder() {
        return getLinesFieldBuilder().addBuilder(
            proto.GridProto.Line.getDefaultInstance());
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public proto.GridProto.Line.Builder addLinesBuilder(
          int index) {
        return getLinesFieldBuilder().addBuilder(
            index, proto.GridProto.Line.getDefaultInstance());
      }
      /**
       * <code>repeated .Line lines = 7;</code>
       */
      public java.util.List<proto.GridProto.Line.Builder> 
           getLinesBuilderList() {
        return getLinesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.GridProto.Line, proto.GridProto.Line.Builder, proto.GridProto.LineOrBuilder> 
          getLinesFieldBuilder() {
        if (linesBuilder_ == null) {
          linesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.GridProto.Line, proto.GridProto.Line.Builder, proto.GridProto.LineOrBuilder>(
                  lines_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          lines_ = null;
        }
        return linesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Grid)
    }

    // @@protoc_insertion_point(class_scope:Grid)
    private static final proto.GridProto.Grid DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.GridProto.Grid();
    }

    public static proto.GridProto.Grid getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Grid>
        PARSER = new com.google.protobuf.AbstractParser<Grid>() {
      public Grid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Grid(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Grid> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Grid> getParserForType() {
      return PARSER;
    }

    public proto.GridProto.Grid getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string date = 4;</code>
     */
    java.lang.String getDate();
    /**
     * <code>string date = 4;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>double x = 5;</code>
     */
    double getX();

    /**
     * <code>double y = 6;</code>
     */
    double getY();
  }
  /**
   * Protobuf type {@code Point}
   */
  public  static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Point)
      PointOrBuilder {
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
      date_ = "";
      x_ = 0D;
      y_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Point(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 41: {

              x_ = input.readDouble();
              break;
            }
            case 49: {

              y_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GridProto.internal_static_Point_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GridProto.internal_static_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GridProto.Point.class, proto.GridProto.Point.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 4;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 5;
    private double x_;
    /**
     * <code>double x = 5;</code>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 6;
    private double y_;
    /**
     * <code>double y = 6;</code>
     */
    public double getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, date_);
      }
      if (x_ != 0D) {
        output.writeDouble(5, x_);
      }
      if (y_ != 0D) {
        output.writeDouble(6, y_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, date_);
      }
      if (x_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, x_);
      }
      if (y_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, y_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.GridProto.Point)) {
        return super.equals(obj);
      }
      proto.GridProto.Point other = (proto.GridProto.Point) obj;

      boolean result = true;
      result = result && getDate()
          .equals(other.getDate());
      result = result && (
          java.lang.Double.doubleToLongBits(getX())
          == java.lang.Double.doubleToLongBits(
              other.getX()));
      result = result && (
          java.lang.Double.doubleToLongBits(getY())
          == java.lang.Double.doubleToLongBits(
              other.getY()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.GridProto.Point parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Point parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GridProto.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GridProto.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.GridProto.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GridProto.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GridProto.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.GridProto.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Point)
        proto.GridProto.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GridProto.internal_static_Point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GridProto.internal_static_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GridProto.Point.class, proto.GridProto.Point.Builder.class);
      }

      // Construct using proto.GridProto.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        date_ = "";

        x_ = 0D;

        y_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GridProto.internal_static_Point_descriptor;
      }

      public proto.GridProto.Point getDefaultInstanceForType() {
        return proto.GridProto.Point.getDefaultInstance();
      }

      public proto.GridProto.Point build() {
        proto.GridProto.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.GridProto.Point buildPartial() {
        proto.GridProto.Point result = new proto.GridProto.Point(this);
        result.date_ = date_;
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GridProto.Point) {
          return mergeFrom((proto.GridProto.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GridProto.Point other) {
        if (other == proto.GridProto.Point.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.GridProto.Point parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.GridProto.Point) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 4;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 4;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 4;</code>
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 4;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <code>double x = 5;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 5;</code>
       */
      public Builder setX(double value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 5;</code>
       */
      public Builder clearX() {
        
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 6;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 6;</code>
       */
      public Builder setY(double value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 6;</code>
       */
      public Builder clearY() {
        
        y_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Point)
    }

    // @@protoc_insertion_point(class_scope:Point)
    private static final proto.GridProto.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.GridProto.Point();
    }

    public static proto.GridProto.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Point(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    public proto.GridProto.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Line)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Point coors = 8;</code>
     */
    java.util.List<proto.GridProto.Point> 
        getCoorsList();
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    proto.GridProto.Point getCoors(int index);
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    int getCoorsCount();
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    java.util.List<? extends proto.GridProto.PointOrBuilder> 
        getCoorsOrBuilderList();
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    proto.GridProto.PointOrBuilder getCoorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Line}
   */
  public  static final class Line extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Line)
      LineOrBuilder {
    // Use Line.newBuilder() to construct.
    private Line(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Line() {
      coors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Line(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                coors_ = new java.util.ArrayList<proto.GridProto.Point>();
                mutable_bitField0_ |= 0x00000001;
              }
              coors_.add(
                  input.readMessage(proto.GridProto.Point.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          coors_ = java.util.Collections.unmodifiableList(coors_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GridProto.internal_static_Line_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GridProto.internal_static_Line_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GridProto.Line.class, proto.GridProto.Line.Builder.class);
    }

    public static final int COORS_FIELD_NUMBER = 8;
    private java.util.List<proto.GridProto.Point> coors_;
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    public java.util.List<proto.GridProto.Point> getCoorsList() {
      return coors_;
    }
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    public java.util.List<? extends proto.GridProto.PointOrBuilder> 
        getCoorsOrBuilderList() {
      return coors_;
    }
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    public int getCoorsCount() {
      return coors_.size();
    }
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    public proto.GridProto.Point getCoors(int index) {
      return coors_.get(index);
    }
    /**
     * <code>repeated .Point coors = 8;</code>
     */
    public proto.GridProto.PointOrBuilder getCoorsOrBuilder(
        int index) {
      return coors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < coors_.size(); i++) {
        output.writeMessage(8, coors_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < coors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, coors_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.GridProto.Line)) {
        return super.equals(obj);
      }
      proto.GridProto.Line other = (proto.GridProto.Line) obj;

      boolean result = true;
      result = result && getCoorsList()
          .equals(other.getCoorsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCoorsCount() > 0) {
        hash = (37 * hash) + COORS_FIELD_NUMBER;
        hash = (53 * hash) + getCoorsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.GridProto.Line parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Line parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Line parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Line parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Line parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GridProto.Line parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GridProto.Line parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GridProto.Line parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GridProto.Line parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.GridProto.Line parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GridProto.Line parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GridProto.Line parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.GridProto.Line prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Line}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Line)
        proto.GridProto.LineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GridProto.internal_static_Line_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GridProto.internal_static_Line_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GridProto.Line.class, proto.GridProto.Line.Builder.class);
      }

      // Construct using proto.GridProto.Line.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCoorsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (coorsBuilder_ == null) {
          coors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          coorsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GridProto.internal_static_Line_descriptor;
      }

      public proto.GridProto.Line getDefaultInstanceForType() {
        return proto.GridProto.Line.getDefaultInstance();
      }

      public proto.GridProto.Line build() {
        proto.GridProto.Line result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.GridProto.Line buildPartial() {
        proto.GridProto.Line result = new proto.GridProto.Line(this);
        int from_bitField0_ = bitField0_;
        if (coorsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            coors_ = java.util.Collections.unmodifiableList(coors_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.coors_ = coors_;
        } else {
          result.coors_ = coorsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GridProto.Line) {
          return mergeFrom((proto.GridProto.Line)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GridProto.Line other) {
        if (other == proto.GridProto.Line.getDefaultInstance()) return this;
        if (coorsBuilder_ == null) {
          if (!other.coors_.isEmpty()) {
            if (coors_.isEmpty()) {
              coors_ = other.coors_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCoorsIsMutable();
              coors_.addAll(other.coors_);
            }
            onChanged();
          }
        } else {
          if (!other.coors_.isEmpty()) {
            if (coorsBuilder_.isEmpty()) {
              coorsBuilder_.dispose();
              coorsBuilder_ = null;
              coors_ = other.coors_;
              bitField0_ = (bitField0_ & ~0x00000001);
              coorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCoorsFieldBuilder() : null;
            } else {
              coorsBuilder_.addAllMessages(other.coors_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.GridProto.Line parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.GridProto.Line) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.GridProto.Point> coors_ =
        java.util.Collections.emptyList();
      private void ensureCoorsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          coors_ = new java.util.ArrayList<proto.GridProto.Point>(coors_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.GridProto.Point, proto.GridProto.Point.Builder, proto.GridProto.PointOrBuilder> coorsBuilder_;

      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public java.util.List<proto.GridProto.Point> getCoorsList() {
        if (coorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(coors_);
        } else {
          return coorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public int getCoorsCount() {
        if (coorsBuilder_ == null) {
          return coors_.size();
        } else {
          return coorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public proto.GridProto.Point getCoors(int index) {
        if (coorsBuilder_ == null) {
          return coors_.get(index);
        } else {
          return coorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder setCoors(
          int index, proto.GridProto.Point value) {
        if (coorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoorsIsMutable();
          coors_.set(index, value);
          onChanged();
        } else {
          coorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder setCoors(
          int index, proto.GridProto.Point.Builder builderForValue) {
        if (coorsBuilder_ == null) {
          ensureCoorsIsMutable();
          coors_.set(index, builderForValue.build());
          onChanged();
        } else {
          coorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder addCoors(proto.GridProto.Point value) {
        if (coorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoorsIsMutable();
          coors_.add(value);
          onChanged();
        } else {
          coorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder addCoors(
          int index, proto.GridProto.Point value) {
        if (coorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoorsIsMutable();
          coors_.add(index, value);
          onChanged();
        } else {
          coorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder addCoors(
          proto.GridProto.Point.Builder builderForValue) {
        if (coorsBuilder_ == null) {
          ensureCoorsIsMutable();
          coors_.add(builderForValue.build());
          onChanged();
        } else {
          coorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder addCoors(
          int index, proto.GridProto.Point.Builder builderForValue) {
        if (coorsBuilder_ == null) {
          ensureCoorsIsMutable();
          coors_.add(index, builderForValue.build());
          onChanged();
        } else {
          coorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder addAllCoors(
          java.lang.Iterable<? extends proto.GridProto.Point> values) {
        if (coorsBuilder_ == null) {
          ensureCoorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, coors_);
          onChanged();
        } else {
          coorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder clearCoors() {
        if (coorsBuilder_ == null) {
          coors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          coorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public Builder removeCoors(int index) {
        if (coorsBuilder_ == null) {
          ensureCoorsIsMutable();
          coors_.remove(index);
          onChanged();
        } else {
          coorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public proto.GridProto.Point.Builder getCoorsBuilder(
          int index) {
        return getCoorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public proto.GridProto.PointOrBuilder getCoorsOrBuilder(
          int index) {
        if (coorsBuilder_ == null) {
          return coors_.get(index);  } else {
          return coorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public java.util.List<? extends proto.GridProto.PointOrBuilder> 
           getCoorsOrBuilderList() {
        if (coorsBuilder_ != null) {
          return coorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(coors_);
        }
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public proto.GridProto.Point.Builder addCoorsBuilder() {
        return getCoorsFieldBuilder().addBuilder(
            proto.GridProto.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public proto.GridProto.Point.Builder addCoorsBuilder(
          int index) {
        return getCoorsFieldBuilder().addBuilder(
            index, proto.GridProto.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .Point coors = 8;</code>
       */
      public java.util.List<proto.GridProto.Point.Builder> 
           getCoorsBuilderList() {
        return getCoorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.GridProto.Point, proto.GridProto.Point.Builder, proto.GridProto.PointOrBuilder> 
          getCoorsFieldBuilder() {
        if (coorsBuilder_ == null) {
          coorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.GridProto.Point, proto.GridProto.Point.Builder, proto.GridProto.PointOrBuilder>(
                  coors_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          coors_ = null;
        }
        return coorsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Line)
    }

    // @@protoc_insertion_point(class_scope:Line)
    private static final proto.GridProto.Line DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.GridProto.Line();
    }

    public static proto.GridProto.Line getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Line>
        PARSER = new com.google.protobuf.AbstractParser<Line>() {
      public Line parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Line(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Line> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Line> getParserForType() {
      return PARSER;
    }

    public proto.GridProto.Line getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Grid_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Grid_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Point_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Line_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Line_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrid.proto\"E\n\004Grid\022\r\n\005index\030\001 \001(\005\022\013\n\003c" +
      "ol\030\002 \001(\005\022\013\n\003row\030\003 \001(\005\022\024\n\005lines\030\007 \003(\0132\005.L" +
      "ine\"+\n\005Point\022\014\n\004date\030\004 \001(\t\022\t\n\001x\030\005 \001(\001\022\t\n" +
      "\001y\030\006 \001(\001\"\035\n\004Line\022\025\n\005coors\030\010 \003(\0132\006.PointB" +
      "\022\n\005protoB\tGridProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Grid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Grid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Grid_descriptor,
        new java.lang.String[] { "Index", "Col", "Row", "Lines", });
    internal_static_Point_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Point_descriptor,
        new java.lang.String[] { "Date", "X", "Y", });
    internal_static_Line_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Line_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Line_descriptor,
        new java.lang.String[] { "Coors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
